# Generated by Django 4.1.4 on 2022-12-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=50)),
                ('highest_degree', models.CharField(max_length=50)),
                ('services_offers', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('password', models.CharField(max_length=50)),
                ('cpassword', models.CharField(max_length=50)),
                ('otp', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
